/*
# Seed AI Concept Relationships

Inserts all concept relationships:
- type 'edge': graph edges for the interactive concept map visualization
- type 'prerequisite': concepts required to understand this concept (source requires target)
- type 'unlocks': concepts this concept opens up (source unlocks target)
- type 'highlight_group': concepts highlighted on the map when hovering source

Uses DELETE + INSERT (truncate-reload) pattern for idempotency on seed data.
*/

DELETE FROM ai_concept_relationships;

INSERT INTO ai_concept_relationships (source_concept_slug, target_concept_slug, relationship_type) VALUES

-- ── GRAPH EDGES (used by ConceptMap visualization) ──────────────────────────
-- Foundation internal
('llms', 'tokens', 'edge'),
('llms', 'context-windows', 'edge'),
('tokens', 'context-windows', 'edge'),
('llms', 'embeddings', 'edge'),
('llms', 'prompt-engineering', 'edge'),
-- Foundation → Knowledge
('embeddings', 'vector-databases', 'edge'),
('embeddings', 'chunking', 'edge'),
('prompt-engineering', 'rag', 'edge'),
-- Knowledge internal
('vector-databases', 'rag', 'edge'),
('vector-databases', 'search', 'edge'),
('knowledge-graphs', 'rag', 'edge'),
('rag', 'chunking', 'edge'),
('chunking', 'metadata', 'edge'),
('metadata', 'search', 'edge'),
('search', 'rag', 'edge'),
-- Knowledge → Intelligence
('rag', 'agents', 'edge'),
('search', 'tool-calling', 'edge'),
('vector-databases', 'memory', 'edge'),
-- Intelligence internal
('tool-calling', 'agents', 'edge'),
('tool-calling', 'mcp', 'edge'),
('mcp', 'agents', 'edge'),
('agents', 'multi-agent-systems', 'edge'),
('agents', 'memory', 'edge'),
('agents', 'planning', 'edge'),
('agents', 'evaluation', 'edge'),
('memory', 'planning', 'edge'),
('planning', 'multi-agent-systems', 'edge'),
('evaluation', 'guardrails', 'edge'),
-- Intelligence → Production
('agents', 'orchestration', 'edge'),
('mcp', 'apis', 'edge'),
('evaluation', 'monitoring', 'edge'),
('guardrails', 'security', 'edge'),
('multi-agent-systems', 'orchestration', 'edge'),
-- Production internal
('apis', 'orchestration', 'edge'),
('orchestration', 'deployment', 'edge'),
('orchestration', 'monitoring', 'edge'),
('monitoring', 'security', 'edge'),
('security', 'deployment', 'edge'),

-- ── PREREQUISITES (source concept requires these concepts first) ─────────────
('tokens', 'llms', 'prerequisite'),
('context-windows', 'llms', 'prerequisite'),
('context-windows', 'tokens', 'prerequisite'),
('embeddings', 'llms', 'prerequisite'),
('prompt-engineering', 'llms', 'prerequisite'),
('prompt-engineering', 'tokens', 'prerequisite'),
('vector-databases', 'embeddings', 'prerequisite'),
('knowledge-graphs', 'embeddings', 'prerequisite'),
('rag', 'llms', 'prerequisite'),
('rag', 'embeddings', 'prerequisite'),
('rag', 'vector-databases', 'prerequisite'),
('rag', 'chunking', 'prerequisite'),
('chunking', 'embeddings', 'prerequisite'),
('metadata', 'chunking', 'prerequisite'),
('search', 'vector-databases', 'prerequisite'),
('search', 'metadata', 'prerequisite'),
('tool-calling', 'llms', 'prerequisite'),
('tool-calling', 'prompt-engineering', 'prerequisite'),
('mcp', 'tool-calling', 'prerequisite'),
('agents', 'llms', 'prerequisite'),
('agents', 'tool-calling', 'prerequisite'),
('agents', 'prompt-engineering', 'prerequisite'),
('multi-agent-systems', 'agents', 'prerequisite'),
('memory', 'agents', 'prerequisite'),
('memory', 'vector-databases', 'prerequisite'),
('planning', 'agents', 'prerequisite'),
('evaluation', 'agents', 'prerequisite'),
('evaluation', 'prompt-engineering', 'prerequisite'),
('guardrails', 'evaluation', 'prerequisite'),
('apis', 'llms', 'prerequisite'),
('apis', 'mcp', 'prerequisite'),
('orchestration', 'agents', 'prerequisite'),
('orchestration', 'apis', 'prerequisite'),
('monitoring', 'evaluation', 'prerequisite'),
('monitoring', 'orchestration', 'prerequisite'),
('security', 'guardrails', 'prerequisite'),
('security', 'monitoring', 'prerequisite'),
('deployment', 'apis', 'prerequisite'),
('deployment', 'orchestration', 'prerequisite'),
('deployment', 'security', 'prerequisite'),

-- ── UNLOCKS (source concept opens up these concepts) ────────────────────────
('llms', 'tokens', 'unlocks'),
('llms', 'context-windows', 'unlocks'),
('llms', 'embeddings', 'unlocks'),
('llms', 'prompt-engineering', 'unlocks'),
('tokens', 'context-windows', 'unlocks'),
('context-windows', 'rag', 'unlocks'),
('context-windows', 'memory', 'unlocks'),
('embeddings', 'vector-databases', 'unlocks'),
('embeddings', 'chunking', 'unlocks'),
('embeddings', 'knowledge-graphs', 'unlocks'),
('prompt-engineering', 'rag', 'unlocks'),
('prompt-engineering', 'agents', 'unlocks'),
('prompt-engineering', 'evaluation', 'unlocks'),
('vector-databases', 'rag', 'unlocks'),
('vector-databases', 'search', 'unlocks'),
('vector-databases', 'memory', 'unlocks'),
('knowledge-graphs', 'rag', 'unlocks'),
('rag', 'agents', 'unlocks'),
('rag', 'orchestration', 'unlocks'),
('chunking', 'rag', 'unlocks'),
('chunking', 'metadata', 'unlocks'),
('metadata', 'search', 'unlocks'),
('search', 'rag', 'unlocks'),
('search', 'tool-calling', 'unlocks'),
('tool-calling', 'agents', 'unlocks'),
('tool-calling', 'mcp', 'unlocks'),
('mcp', 'agents', 'unlocks'),
('mcp', 'apis', 'unlocks'),
('agents', 'multi-agent-systems', 'unlocks'),
('agents', 'memory', 'unlocks'),
('agents', 'planning', 'unlocks'),
('agents', 'orchestration', 'unlocks'),
('multi-agent-systems', 'orchestration', 'unlocks'),
('memory', 'planning', 'unlocks'),
('planning', 'multi-agent-systems', 'unlocks'),
('evaluation', 'guardrails', 'unlocks'),
('evaluation', 'monitoring', 'unlocks'),
('guardrails', 'security', 'unlocks'),
('guardrails', 'deployment', 'unlocks'),
('apis', 'orchestration', 'unlocks'),
('apis', 'deployment', 'unlocks'),
('orchestration', 'deployment', 'unlocks'),
('orchestration', 'monitoring', 'unlocks'),
('monitoring', 'security', 'unlocks'),
('security', 'deployment', 'unlocks'),

-- ── HIGHLIGHT GROUP (concepts lit up when hovering source on map) ────────────
('llms', 'tokens', 'highlight_group'),
('llms', 'context-windows', 'highlight_group'),
('llms', 'embeddings', 'highlight_group'),
('llms', 'prompt-engineering', 'highlight_group'),
('tokens', 'llms', 'highlight_group'),
('tokens', 'context-windows', 'highlight_group'),
('context-windows', 'llms', 'highlight_group'),
('context-windows', 'tokens', 'highlight_group'),
('context-windows', 'rag', 'highlight_group'),
('context-windows', 'memory', 'highlight_group'),
('embeddings', 'llms', 'highlight_group'),
('embeddings', 'vector-databases', 'highlight_group'),
('embeddings', 'chunking', 'highlight_group'),
('embeddings', 'knowledge-graphs', 'highlight_group'),
('prompt-engineering', 'llms', 'highlight_group'),
('prompt-engineering', 'rag', 'highlight_group'),
('prompt-engineering', 'agents', 'highlight_group'),
('prompt-engineering', 'evaluation', 'highlight_group'),
('vector-databases', 'embeddings', 'highlight_group'),
('vector-databases', 'rag', 'highlight_group'),
('vector-databases', 'search', 'highlight_group'),
('vector-databases', 'memory', 'highlight_group'),
('knowledge-graphs', 'embeddings', 'highlight_group'),
('knowledge-graphs', 'rag', 'highlight_group'),
('rag', 'embeddings', 'highlight_group'),
('rag', 'vector-databases', 'highlight_group'),
('rag', 'chunking', 'highlight_group'),
('rag', 'prompt-engineering', 'highlight_group'),
('rag', 'llms', 'highlight_group'),
('rag', 'search', 'highlight_group'),
('chunking', 'embeddings', 'highlight_group'),
('chunking', 'rag', 'highlight_group'),
('chunking', 'metadata', 'highlight_group'),
('metadata', 'chunking', 'highlight_group'),
('metadata', 'search', 'highlight_group'),
('metadata', 'rag', 'highlight_group'),
('search', 'vector-databases', 'highlight_group'),
('search', 'metadata', 'highlight_group'),
('search', 'rag', 'highlight_group'),
('search', 'tool-calling', 'highlight_group'),
('tool-calling', 'llms', 'highlight_group'),
('tool-calling', 'prompt-engineering', 'highlight_group'),
('tool-calling', 'agents', 'highlight_group'),
('tool-calling', 'mcp', 'highlight_group'),
('mcp', 'tool-calling', 'highlight_group'),
('mcp', 'agents', 'highlight_group'),
('mcp', 'apis', 'highlight_group'),
('agents', 'tool-calling', 'highlight_group'),
('agents', 'mcp', 'highlight_group'),
('agents', 'memory', 'highlight_group'),
('agents', 'planning', 'highlight_group'),
('agents', 'evaluation', 'highlight_group'),
('multi-agent-systems', 'agents', 'highlight_group'),
('multi-agent-systems', 'planning', 'highlight_group'),
('multi-agent-systems', 'orchestration', 'highlight_group'),
('memory', 'agents', 'highlight_group'),
('memory', 'vector-databases', 'highlight_group'),
('memory', 'planning', 'highlight_group'),
('planning', 'agents', 'highlight_group'),
('planning', 'memory', 'highlight_group'),
('planning', 'multi-agent-systems', 'highlight_group'),
('evaluation', 'agents', 'highlight_group'),
('evaluation', 'guardrails', 'highlight_group'),
('evaluation', 'monitoring', 'highlight_group'),
('guardrails', 'evaluation', 'highlight_group'),
('guardrails', 'security', 'highlight_group'),
('guardrails', 'deployment', 'highlight_group'),
('apis', 'llms', 'highlight_group'),
('apis', 'mcp', 'highlight_group'),
('apis', 'orchestration', 'highlight_group'),
('orchestration', 'agents', 'highlight_group'),
('orchestration', 'apis', 'highlight_group'),
('orchestration', 'monitoring', 'highlight_group'),
('orchestration', 'deployment', 'highlight_group'),
('monitoring', 'evaluation', 'highlight_group'),
('monitoring', 'orchestration', 'highlight_group'),
('monitoring', 'security', 'highlight_group'),
('security', 'guardrails', 'highlight_group'),
('security', 'monitoring', 'highlight_group'),
('security', 'deployment', 'highlight_group'),
('deployment', 'apis', 'highlight_group'),
('deployment', 'orchestration', 'highlight_group'),
('deployment', 'security', 'highlight_group'),
('deployment', 'monitoring', 'highlight_group');
